### ISSUE TITLE
Bug: Plugin BlueMap-Towny v2.1.1 generated an exception while executing task 37

### ISSUE THREAD

**Issue by Ubivis** [Chicken/BlueMap-Towny#16]
**Description of the bug**

Plugin raises endless warnings

`[BlueMap-Towny] Plugin BlueMap-Towny v2.1.1 generated an exception while executing task 37
java.lang.NoSuchMethodError: 'java.lang.String net.milkbowl.vault2.economy.Economy.format(java.lang.String, java.math.BigDecimal)'
	at towny-0.100.4.14.jar/com.palmergames.bukkit.towny.object.economy.adapter.VaultUnlockedEconomyAdapter.getFormattedBalance(VaultUnlockedEconomyAdapter.java:78) ~[towny-0.100.4.14.jar:?]
	at towny-0.100.4.14.jar/com.palmergames.bukkit.towny.TownyEconomyHandler.getFormattedBalance(TownyEconomyHandler.java:349) ~[towny-0.100.4.14.jar:?]
	at BlueMap-Towny-2.1.1.jar/codes.antti.bluemaptowny.BlueMapTowny.fillPlaceholders(BlueMapTowny.java:185) ~[BlueMap-Towny-2.1.1.jar:?]
	at BlueMap-Towny-2.1.1.jar/codes.antti.bluemaptowny.BlueMapTowny.lambda$updateMarkers$14(BlueMapTowny.java:275) ~[BlueMap-Towny-2.1.1.jar:?]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
	at BlueMap-Towny-2.1.1.jar/codes.antti.bluemaptowny.BlueMapTowny.lambda$updateMarkers$15(BlueMapTowny.java:270) ~[BlueMap-Towny-2.1.1.jar:?]
	at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at BlueMap-Towny-2.1.1.jar/codes.antti.bluemaptowny.BlueMapTowny.updateMarkers(BlueMapTowny.java:261) ~[BlueMap-Towny-2.1.1.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78) ~[paper-1.21.3.jar:1.21.3-63-4190ee7]
	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.3.jar:1.21.3-63-4190ee7]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.3.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]`

**Reproducing**

1. Install latest PaperMC, TownyAdvanced, BlueMap-Towny
2. I'm not sure if this might be also important, I'm using TheNextEconomy (Paper Version) and VaultUnlocked-2.3.0

**Expected behavior**

Plugin not throwing endless warnings

**Comment by Ubivis** [comment]
Sorry, was my fault, I hadn't the latest ProtocolLib installed (there was an beta for the latest paper, that solved the problem)
