### ISSUE TITLE
Bug: Unable to load BlueMap-Towny -- NoSuchMethodError

### ISSUE THREAD

**Issue by Firav** [Chicken/BlueMap-Towny#5]
**Description of the bug**

Upon loading of the plugin on server start, large thread errors being to propagate. Continue every refresh interval.

```
[19:14:50] [Craft Scheduler Thread - 7 - BlueMap/INFO]: [BlueMap] Loaded!
[19:14:50] [Server thread/WARN]: [BlueMap-Towny] Task #232 for BlueMap-Towny v2.0.0 generated an exception
java.lang.NoSuchMethodError: 'boolean com.palmergames.bukkit.towny.object.Town.isBANG()'
	at codes.antti.bluemaptowny.BlueMapTowny.fillPlaceholders(BlueMapTowny.java:186) ~[BlueMap-Towny-2.0.0.jar:?]
	at codes.antti.bluemaptowny.BlueMapTowny.lambda$updateMarkers$13(BlueMapTowny.java:261) ~[BlueMap-Towny-2.0.0.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at codes.antti.bluemaptowny.BlueMapTowny.lambda$updateMarkers$14(BlueMapTowny.java:254) ~[BlueMap-Towny-2.0.0.jar:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at codes.antti.bluemaptowny.BlueMapTowny.updateMarkers(BlueMapTowny.java:245) ~[BlueMap-Towny-2.0.0.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-81]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1480) ~[paper-1.20.1.jar:git-Paper-81]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-81]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Reproducing**

Steps to produce the issue:
1. Install plugin
2. Start server

**Expected behavior**

No console errors and load map regions.

**Versions**

Paper: 1.20.1-R0.1-SNAP git-Paper-81
Towny: 0.100.0.14
Vault: v1.7.3-b131
BlueMap-Towny: 2.0.0

**Comment by Chicken** [comment]
Fixed in https://github.com/Chicken/BlueMap-Towny/releases/tag/2.0.1
